### PR TITLE
Unbreak build on FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by 4b1eaaf731b0e29497.

```
$ pkg info -x json-c
json-c-0.13.1

$ pkg-config json-c --cflags
-I/usr/local/include/json-c
```
```c
../swaymsg/main.c:12:10: fatal error: 'json-c/json.h' file not found
#include <json-c/json.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

### CODE REVIEW

**Comment by RedSoxFan** [comment]
Thanks!
