### ISSUE TITLE
Sway 1.5-rc1 fails to compile with wlroots-0.10.1

### ISSUE THREAD

**Issue by eternal-sorrow** [swaywm/sway#5479]
```
In file included from ../sway-1.5-rc1/include/sway/tree/view.h:9,
                 from ../sway-1.5-rc1/include/sway/criteria.h:7,
                 from ../sway-1.5-rc1/sway/commands.c:11:
../sway-1.5-rc1/include/sway/input/input-manager.h:5:10: fatal error: wlr/types/wlr_keyboard_shortcuts_inhibit_v1.h: No such file or directory
    5 | #include <wlr/types/wlr_keyboard_shortcuts_inhibit_v1.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Maybe make a release of wlroots with all the required features and set the correct dependencies?

**Comment by eternal-sorrow** [comment]
Compiled successfully with this commit version: https://github.com/swaywm/wlroots/commit/9e68ed21599661f75f3b73e3e698ab8828341a18

**Comment by emersion** [comment]
Yeah, so about this... I'm not sure what the best strategy is. If there's a bug in the RC, it isn't likely that fixing the bug requires a new wlroots commit. If we choose to release a new wlroots release at each Sway RC release, this will result in unnecessary churn.

Maybe we should release a new wlroots version at the Sway RC1, then make a wlroots bugfix release if necessary at each Sway release (RC or final).

**Comment by primeos** [comment]
Another option might be to announce a recommended wlroots commit like it was done during the alpha releases for Sway 1.0, e.g.: https://github.com/swaywm/sway/releases/tag/1.0-alpha.6 (or alternatively maybe to a branch).

Without any references I'd assume one should just use the most recent commit from wlroots' `master` branch, which would also be fine for me.

> It's also happened in the past that a wlroots breaking change happened during the Sway RCs (to fix a bug iirc).

If there where no breaking changes or a low enough probability it might make sense to create an RC for the wlroots release so that other projects could also prepare (AFAIK they track master anyway, but maybe they want to prepare for releases in advance without tracking Sway releases).

Anyway, from my perspective (as downstream package maintainer) wlroots RCs aren't really required as long as the next wlroots release for Sway 1.5 is based on the most recent commit of the master branch (or another known branch).

**Comment by eternal-sorrow** [comment]
>Compiled successfully with this commit version: swaywm/wlroots@9e68ed2

Nevermind that. Using sway built against this commit caused continuous flickering of Firefox window. I built the wlroots from master and the issue disappeared.

**Comment by emersion** [comment]
Added a note about the wlroots commit to use in the release description.

**Comment by jubalh** [comment]
Personally I stopped doing RCs for the software I release. I just use point releases for the fixes that people encounter in the new major version.
It seems less a hassle to me. It would also help in this situation for sway/wlroots I think. I also don't see any downside for it. Most distro are too slow to get the first major release in their repos anyways, so the bugfix will be already out two weeks after the major or something like that. And that one gets into the repos.

**Comment by luispabon** [comment]
My 2p, as long as you don't consider wlroots deserves a 1.0 release based on its published interfaces and features, it is OK to release it in lockstep with sway. In the understanding it is a temporary situation.

**Comment by jubalh** [comment]
> My 2p, as long as you don't consider wlroots deserves a 1.0 release based on its published interfaces and features, it is OK to release it in lockstep with sway. In the understanding it is a temporary situation.

Surely it is "OK". But it was just mentioned that another way has some advantages. So you came here to tell us your opinion or can you name advantages and disadvantages of your proposal?

**Comment by luispabon** [comment]
I should think maintaining the status quo for a bit longer has obvious advantages when the software in question hasn't reached a level of maturity that they can be released indepedently of each other. Sway really is the main show and tell for wlroots, it has a hard dependency on it, a lot of wlroots development is driven by the real usage of the library by sway and its users, and wlroots is not feature complete, or it would've warranted a 1.x release by now. No reason to artificially hold sway or wlroots' development back in the name of avoiding BC breakage as long as wlroots interface hasn't reached maturity.

**Comment by jubalh** [comment]
I'm sorry but this doesn't address anything that has been said or is discussed here.

**Comment by emersion** [comment]
Will release a new version next RC.

**Comment by ddevault** [comment]
Err, sorry, this was a misunderstanding. The Sway release candidates have always depended on wlroots master at the time the RC is shipped - we only ship wlroots releases when we prepare the final sway release. Avoids some churn.
