### ISSUE TITLE
Fails to build with GCC 8.1.0

### ISSUE THREAD

**Issue by xyproto** [swaywm/sway#1931]
```
/home/afr/archpackages/sway-git/src/sway/swaygrab/main.c: In function ‘default_filename’:
/home/afr/archpackages/sway-git/src/sway/swaygrab/main.c:160:2: error: ‘strncat’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
  strncat(filename, extension, ext_len);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/afr/archpackages/sway-git/src/sway/swaygrab/main.c:153:16: note: length computed here
  int ext_len = strlen(extension);
                ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [swaygrab/CMakeFiles/swaygrab.dir/build.make:63: swaygrab/CMakeFiles/swaygrab.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:770: swaygrab/CMakeFiles/swaygrab.dir/all] Error 2
```

This is with GCC 8.1.0 on 64-bit Arch Linux, using the latest commit of sway: 73cc92213f704948f9a13539247c978f79a4e915

**Comment by xyproto** [comment]
When building with `-w` (ignoring warnings), it works.

**Comment by xyproto** [comment]
I was using the unofficial sway-git package from AUR. Will check.

**Comment by xyproto** [comment]
The package was (incorrectly) using the 0.15 branch. Will check again with master.

**Comment by RyanDwyer** [comment]
The sway-git AUR package is intentionally using the 0.15 branch. 0.15 is stable and uses CMake. The master branch is 1.0-alpha and uses Meson.

**Comment by xyproto** [comment]
Sway master works perfectly with GCC 8.1.0!

I was confused by the `sway-git` package being bound to 0.15, I will ask the current maintainer to change it.

Sorry for the noise and thanks for the responses.
