### PR TITLE
Fix overflow in strcpy

### LINKED ISSUE #2863: Compilation produces memory overflow warnings
When upgrading `sway-wlroots-git`, these warnings are produced:
```
In file included from /usr/include/string.h:494,
                 from /usr/include/glib-2.0/glib/gtestutils.h:30,
                 from /usr/include/glib-2.0/glib.h:85,
                 from /usr/include/pango-1.0/pango/pango-coverage.h:25,
                 from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/pango-1.0/pango/pangocairo.h:25,
                 from ../sway/common/pango.c:2:
In function ‘strcpy’,
    inlined from ‘get_text_size’ at ../sway/common/pango.c:95:3:
/usr/include/bits/string_fortified.h:90:10: warning: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Wstringop-overflow=]
   return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strcpy’,
    inlined from ‘pango_printf’ at ../sway/common/pango.c:115:3:
/usr/include/bits/string_fortified.h:90:10: warning: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Wstringop-overflow=]
   return __builtin___strcpy_chk (__dest, __src, __bos (__dest));

```
I am running `gcc 8.2.1 20180831`, on Arch Linux.

### PR DESCRIPTION
**Pull request by SpeedJack**
Compiling current master:
```
In function ‘strcpy’,
    inlined from ‘get_text_size’ at ../sway-9999/common/pango.c:95:3:
/usr/include/bits/string_fortified.h:90:10: error: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
   return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strcpy’,
    inlined from ‘pango_printf’ at ../sway-9999/common/pango.c:115:3:
/usr/include/bits/string_fortified.h:90:10: error: ‘__builtin___memcpy_chk’ writing 18 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
   return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Introduced in #2843 

Cause:
```c
char* overflow = "[buffer overflow]";
sizeof(overflow); /* = sizeof(char*) = 8 (WRONG) */
```
```c
char overflow[] = "[buffer overflow]";
sizeof(overflow); /* = 18 (CORRECT) */
```
Fixes #2863

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Good catch. Thanks!
