### ISSUE TITLE
get_current_time_msec conflicts with wlroots symbol

### ISSUE THREAD

**Issue by jbeich** [swaywm/sway#5514]
Regressed by d7900c6e5e82
```c
$ meson -Dwlroots:default_library=static _build
$ meson compile -C _build
[...]
ld: error: duplicate symbol: get_current_time_msec
>>> defined at util.c:13 (../common/util.c:13)
>>>            util.c.o:(get_current_time_msec) in archive common/libsway-common.a
>>> defined at time.c:13 (../subprojects/wlroots/util/time.c:13)
>>>            util_time.c.o:(.text+0xA0) in archive subprojects/wlroots/libwlroots.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by emersion** [comment]
Ref https://github.com/swaywm/wlroots/issues/1892

**Comment by illiliti** [comment]
It builds just fine nowadays.

**Comment by emersion** [comment]
Let's keep tracking this kind of issue on the wlroots side: https://gitlab.freedesktop.org/wlroots/wlroots/-/work_items/1892
